# This workflow will install Python dependencies, run tests and lint with a
#  single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint, Style & Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - "*.rst"
      - "LICENSE"
      - "requirements_test.txt"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - "*.rst"
      - "LICENSE"
      - "requirements_test.txt"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Upgrade PIP
      run: |
        python -m pip install --upgrade pip

    - name: Install Python testing dependencies
      run: |
        make install_requirements_test

    - name: Install Python program in 'develop' mode
      run: |
        make install_requirements develop

    - name: Lint with pylint
      run: |
        make lint

    - name: Style-check with flake8
      run: |
        make flake8

    - name: Test with pytest
      run: |
        make pytest
